# Generated by Django 3.1.7 on 2021-10-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20211009_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='icon',
            field=models.ImageField(blank=True, default='images/no_img.png', upload_to=''),
        ),
    ]
