# Generated by Django 3.1.7 on 2021-03-15 22:41

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210314_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[account.validators.participant_code_not_zero]),
        ),
    ]
