# Generated by Django 3.1.7 on 2021-03-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210316_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_activate_user', 'Can activate user')]},
        ),
    ]
