# Generated by Django 3.1.7 on 2021-03-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210317_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_activate_user', 'Can activate user'), ('can_assing_role', 'Can assing role')]},
        ),
    ]
